"""
Database module for SQLAlchemy models, engine setup, and session management.
"""

from datetime import datetime, timezone
from typing import Generator, Optional
from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    create_engine,
)
from sqlalchemy.orm import (
    DeclarativeBase,
    Relationship,
    Session,
    mapped_column,
    relationship,
    sessionmaker,
)

from scrapper.config import settings


class Base(DeclarativeBase):
    """Base class for all SQLAlchemy declarative models."""
    pass


def utc_now():
    return datetime.now(timezone.utc)


class Competitor(Base):
    """Monitored target accounts."""
    __tablename__ = "competitors"

    id = mapped_column(Integer, primary_key=True, autoincrement=True)
    username = mapped_column(String(100), unique=True, nullable=False, index=True)
    platform = mapped_column(String(50), default="instagram", nullable=False)
    median_views = mapped_column(Integer, default=0, nullable=False)
    created_at = mapped_column(DateTime, default=utc_now, nullable=False)
    updated_at = mapped_column(DateTime, default=utc_now, onupdate=utc_now, nullable=False)

    # Relationships
    reels: Relationship[list["Reel"]] = relationship("Reel", back_populates="competitor", cascade="all, delete-orphan")
    scrape_runs: Relationship[list["ScrapeRun"]] = relationship("ScrapeRun", back_populates="competitor", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Competitor(id={self.id}, username='{self.username}', median_views={self.median_views})>"


class Reel(Base):
    """Scraped video posts."""
    __tablename__ = "reels"

    id = mapped_column(Integer, primary_key=True, autoincrement=True)
    competitor_id = mapped_column(Integer, ForeignKey("competitors.id", ondelete="CASCADE"), nullable=False, index=True)
    shortcode = mapped_column(String(50), unique=True, nullable=False, index=True)
    url = mapped_column(Text, nullable=False)
    views = mapped_column(Integer, default=0, nullable=False)
    likes = mapped_column(Integer, default=0, nullable=False)
    comments = mapped_column(Integer, default=0, nullable=False)
    shares = mapped_column(Integer, default=0, nullable=False)
    duration_secs = mapped_column(Float, default=0.0, nullable=False)
    caption = mapped_column(Text, nullable=True)
    is_outlier = mapped_column(Boolean, default=False, nullable=False, index=True)
    audio_path = mapped_column(String(500), nullable=True)
    published_at = mapped_column(DateTime, nullable=False)
    scraped_at = mapped_column(DateTime, default=utc_now, nullable=False)

    # Relationships
    competitor: Relationship["Competitor"] = relationship("Competitor", back_populates="reels")
    analysis: Relationship[Optional["AIAnalysis"]] = relationship("AIAnalysis", back_populates="reel", uselist=False, cascade="all, delete-orphan")

    @property
    def engagement_rate(self) -> float:
        """Calculate engagement rate based on views."""
        if self.views > 0:
            return (self.likes + self.comments + self.shares) / self.views
        return 0.0

    def __repr__(self) -> str:
        return f"<Reel(id={self.id}, shortcode='{self.shortcode}', views={self.views}, is_outlier={self.is_outlier})>"


class AIAnalysis(Base):
    """Cognitive and hook analysis generated by LLM and Whisper."""
    __tablename__ = "ai_analysis"

    id = mapped_column(Integer, primary_key=True, autoincrement=True)
    reel_id = mapped_column(Integer, ForeignKey("reels.id", ondelete="CASCADE"), unique=True, nullable=False, index=True)
    transcript = mapped_column(Text, nullable=True)
    hook_text = mapped_column(Text, nullable=True)
    hook_type = mapped_column(String(100), nullable=True)
    hook_score = mapped_column(Integer, nullable=True)
    psychological_trigger = mapped_column(Text, nullable=True)
    generated_script = mapped_column(Text, nullable=True)
    model_used = mapped_column(String(100), default="gemini-2.5-flash", nullable=False)
    prompt_version = mapped_column(String(50), default="v1.0", nullable=False)
    created_at = mapped_column(DateTime, default=utc_now, nullable=False)

    # Relationships
    reel: Relationship["Reel"] = relationship("Reel", back_populates="analysis")

    def __repr__(self) -> str:
        return f"<AIAnalysis(id={self.id}, reel_id={self.reel_id}, hook_type='{self.hook_type}', hook_score={self.hook_score})>"


class ScrapeRun(Base):
    """Audit log for pipeline execution runs."""
    __tablename__ = "scrape_runs"

    id = mapped_column(Integer, primary_key=True, autoincrement=True)
    competitor_id = mapped_column(Integer, ForeignKey("competitors.id", ondelete="CASCADE"), nullable=False, index=True)
    started_at = mapped_column(DateTime, default=utc_now, nullable=False)
    finished_at = mapped_column(DateTime, nullable=True)
    status = mapped_column(String(50), default="running", nullable=False)  # running, completed, failed
    posts_fetched = mapped_column(Integer, default=0, nullable=False)
    outliers_found = mapped_column(Integer, default=0, nullable=False)
    error_message = mapped_column(Text, nullable=True)

    # Relationships
    competitor: Relationship["Competitor"] = relationship("Competitor", back_populates="scrape_runs")

    def __repr__(self) -> str:
        return f"<ScrapeRun(id={self.id}, competitor_id={self.competitor_id}, status='{self.status}')>"


def get_db_url() -> str:
    """Return SQLite database connection URL."""
    settings.ensure_directories()
    return f"sqlite:///{settings.absolute_db_path.as_posix()}"


_engine = None
_SessionFactory = None


def get_engine():
    """Get or create singleton SQLAlchemy engine."""
    global _engine
    if _engine is None:
        _engine = create_engine(
            get_db_url(),
            echo=False,
            connect_args={"check_same_thread": False},
        )
    return _engine


def get_session_factory():
    """Get or create sessionmaker factory."""
    global _SessionFactory
    if _SessionFactory is None:
        _SessionFactory = sessionmaker(bind=get_engine(), autoflush=False, autocommit=False)
    return _SessionFactory


def get_db() -> Generator[Session, None, None]:
    """Contextual database session generator."""
    factory = get_session_factory()
    session = factory()
    try:
        yield session
    finally:
        session.close()


def init_db() -> None:
    """Initialize database tables and directories."""
    settings.ensure_directories()
    engine = get_engine()
    Base.metadata.create_all(bind=engine)
